markdown: kramdown
highlighter: false
plugins: ./_plugins
paginate: 10
safe: false

#站点基础配置
title: Kewei's whereabouts
subTitle: Vim Kewei.c
description: 如鱼得水
url: http://keweihk.com
feed: /atom.xml

#菜单配置
nav:
  - text: Home
    url: /index.html
    icon: icon-home
    class: home
  - text: Archives
    url: /archives.html
    icon: icon-reorder
    class: none
  - text: About Me 
    url: /contact.html
    icon: icon-user
    class: none
  - text: Github
    url: https://github.com/keweiyu
    icon: icon-github
    class: none
#  - text: Linkedin
#    url: http://cn.linkedin.com/in/chaominchen
#    icon: icon-linkedin
#    class: none
  # - text: 联系我
  #   url: http://www.zhanxin.info/contact.html
  #   icon: icon-heart
  #   class: none
  # - text: 博客源代码
  #   url: https://github.com/pizn/iLotus
  #   icon: icon-github
  #   class: none

page:
  - text: Google
    url: http://www.gfsoso.com/
    last: true
  # - text: 喜欢的网站
  #   url: /links.html
  #   last: true
#  - text: Linkedin
#    url: http://cn.linkedin.com/
#    icon: icon-linkedin
#    class: none
#  - text: Github
#    url: https://github.com/keweiyu
#    icon: icon-github
#    class: none
#评论信息
disqus:
  config: false
  id: m
duoshuo:
  config: true
  id: keweiyu

author:
  name: Kewei Yu
